### ISSUE TITLE
Вопрос касательно erela.js-vk и erela.js || Проблема с плагинами

### ISSUE THREAD

**Issue by styleryt3** [nik9play/vk-music-bot#17]
Привет! Захотел встроить в своего бота проигрывание музыки не только с YouTube и Spotify, а и ВК, но плагина не нашел, только этот репозиторий. Так вот, в чем разница erela.js-vk и erela.js, и можно ли использовать обычный erela.js, для проигрывания музыки из VK, если нет, то как встроить его к паре с обычным erela.js. Наперёд спасибо!

**Comment by nik9play** [comment]
В erela.js-vk я добавил метод buildUnresolvedQuery в класс Utils, который позволяет сделать UnresolvedTrack из ссылки на mp3. 
Обычный buildUnresolved работал только с ютубом.
Это форк erela.js, поэтому можно использовать либо то, либо это.

**Comment by styleryt3** [comment]
Когда erela.js обновят, тут обнову добавят?

**Comment by nik9play** [comment]
Скорее всего да

**Comment by styleryt3** [comment]
Окей, спасибо, результатом поделюсь тут же)

**Comment by styleryt3** [comment]
Снова привет, попытался запустить с плагином erela.js-spotify, но тот выдает ошибку RangeError: Plugin at index 0 does not extend Plugin. Может проблема в том, что плагины используют шаблон структуры не из форк erela.js-vk, а из обычного erela.js?

**Comment by styleryt3** [comment]
Без плагинов при попытке включить музыку на erela.js-vk в консоли ошибка 
Error: Unknown file format.
    at Object.run (W:\Projects\imger\commands\Музыка\play.js:36:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
как и с обычным erela.js
