### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by numarkpro** [nik9play/vk-music-bot#25]
![image](https://user-images.githubusercontent.com/73024472/164944543-d4bd7833-ddc7-47ff-bd18-da1294bcac50.png)

**Comment by nik9play** [comment]
Надо указать следующие переменные окружения:
```
DISCORD_TOKEN=xxxxxxxx
STATS_KEY=xxxxxxxxx
LAVALINK_NODES=lavalink-node-1,localhost,5000,xxxxxxx
MONGO_URL=mongodb://localhost:27017/vkmusicbot_db
REDIS_URL=redis://localhost:6379/
API_TOKEN=xxxxxxxx
DATMUSIC_URL=http://0.0.0.0/
```

**Comment by numarkpro** [comment]
apitoken чего?

**Comment by nik9play** [comment]
Приватного апи, которое используется ботом. На него можно забить

**Comment by numarkpro** [comment]
![image](https://user-images.githubusercontent.com/73024472/164972698-04d1cffb-9503-4b42-85e0-0562715b73fe.png)
всё правильно записанно а бот не хочет запускаться

**Comment by nik9play** [comment]
Прикладывайте логи всегда, когда пишите, что что-то не запускается
