### ISSUE TITLE
Не может найти трек с "отрицательным" ID

### ISSUE THREAD

**Issue by quilin** [nik9play/vk-music-bot#8]
У некоторых треков в VK ID начинается с минуса - например если искать по названию "Astral Plane NWN 2: Mask of the Betrayer OST" - то у первого же будет идентификатор `-38989182_434728219`. Этот трек явно в открытом доступе, но не проигрывается тем не менее.

**Comment by nik9play** [comment]
И правда. Видимо что-то с правами доступа. Буду смотреть

**Comment by nik9play** [comment]
Проблема оказалось с regex вот [здесь](https://github.com/nik9play/vk-music-bot/blob/8f7f8fe7283cf2feeeb89dcb2b2d018ab73088b7/vkApi/audioGetOne.js#L49). Он просто не воспринимал айди с минусом как айди. Сейчас буду чинить.

**Comment by quilin** [comment]
Спасибо за быстрость!
